/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Reaction } from "./Reaction";
import { ReactionCountArgs } from "./ReactionCountArgs";
import { ReactionFindManyArgs } from "./ReactionFindManyArgs";
import { ReactionFindUniqueArgs } from "./ReactionFindUniqueArgs";
import { CreateReactionArgs } from "./CreateReactionArgs";
import { UpdateReactionArgs } from "./UpdateReactionArgs";
import { DeleteReactionArgs } from "./DeleteReactionArgs";
import { Comment } from "../../comment/base/Comment";
import { Post } from "../../post/base/Post";
import { ReactionService } from "../reaction.service";
@graphql.Resolver(() => Reaction)
export class ReactionResolverBase {
  constructor(protected readonly service: ReactionService) {}

  async _reactionsMeta(
    @graphql.Args() args: ReactionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Reaction])
  async reactions(
    @graphql.Args() args: ReactionFindManyArgs
  ): Promise<Reaction[]> {
    return this.service.reactions(args);
  }

  @graphql.Query(() => Reaction, { nullable: true })
  async reaction(
    @graphql.Args() args: ReactionFindUniqueArgs
  ): Promise<Reaction | null> {
    const result = await this.service.reaction(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Reaction)
  async createReaction(
    @graphql.Args() args: CreateReactionArgs
  ): Promise<Reaction> {
    return await this.service.createReaction({
      ...args,
      data: {
        ...args.data,

        comment: args.data.comment
          ? {
              connect: args.data.comment,
            }
          : undefined,

        post: args.data.post
          ? {
              connect: args.data.post,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Reaction)
  async updateReaction(
    @graphql.Args() args: UpdateReactionArgs
  ): Promise<Reaction | null> {
    try {
      return await this.service.updateReaction({
        ...args,
        data: {
          ...args.data,

          comment: args.data.comment
            ? {
                connect: args.data.comment,
              }
            : undefined,

          post: args.data.post
            ? {
                connect: args.data.post,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Reaction)
  async deleteReaction(
    @graphql.Args() args: DeleteReactionArgs
  ): Promise<Reaction | null> {
    try {
      return await this.service.deleteReaction(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Comment, {
    nullable: true,
    name: "comment",
  })
  async getComment(
    @graphql.Parent() parent: Reaction
  ): Promise<Comment | null> {
    const result = await this.service.getComment(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Post, {
    nullable: true,
    name: "post",
  })
  async getPost(@graphql.Parent() parent: Reaction): Promise<Post | null> {
    const result = await this.service.getPost(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
